"""add_finding_records

Revision ID: 0db2a5c54366
Revises: a9c4e21f8b03
Create Date: 2026-06-22 12:38:30.398145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '0db2a5c54366'
down_revision: Union[str, Sequence[str], None] = 'a9c4e21f8b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_scan_id', sa.Integer(), nullable=False),
    sa.Column('advisory_id', sa.String(length=200), nullable=False),
    sa.Column('package', sa.String(length=200), nullable=False),
    sa.Column('ecosystem', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'warning', 'low', 'info', name='alertseverity'), nullable=False),
    sa.Column('first_found_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('closed_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('accepted_by_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('accepted_reason', sa.String(length=1000), nullable=True),
    sa.Column('accepted_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_scan_id'], ['repo_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_records', schema=None) as batch_op:
        batch_op.create_index('ix_finding_records_closed_at', ['closed_at'], unique=False)
        batch_op.create_index('ix_finding_records_identity', ['repo_scan_id', 'advisory_id', 'package', 'ecosystem'], unique=False)

    with op.batch_alter_table('repo_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_high_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sla_medium_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo_scans', schema=None) as batch_op:
        batch_op.drop_column('sla_medium_days')
        batch_op.drop_column('sla_high_days')

    with op.batch_alter_table('finding_records', schema=None) as batch_op:
        batch_op.drop_index('ix_finding_records_identity')
        batch_op.drop_index('ix_finding_records_closed_at')

    op.drop_table('finding_records')
    # ### end Alembic commands ###
