"""add_finding_detail_columns

Revision ID: 4a2db4ae3d0b
Revises: 0db2a5c54366
Create Date: 2026-06-23 08:00:25.969568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2db4ae3d0b'
down_revision: Union[str, Sequence[str], None] = '0db2a5c54366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('package_version', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fixed_versions', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_malicious', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_records', schema=None) as batch_op:
        batch_op.drop_column('is_malicious')
        batch_op.drop_column('url')
        batch_op.drop_column('fixed_versions')
        batch_op.drop_column('package_version')
        batch_op.drop_column('details')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
